---
- hosts: '{{ host }}'
  gather_facts: true
  remote_user: ubuntu
  roles:
  - users-admin
  - packages
  - hostname

# ansible-playbook -diff --ask-vault-pass -e "host=inventoryName" provisioning.yml
